### ISSUE TITLE
Cannot locate maxminddb during configure

### ISSUE THREAD

**Issue by cilia** [leev/ngx_http_geoip2_module#10]
Hi,

I have compiled and installed libmaxminddb library from MaxMind as per their instructions, and "ldconfig -p | grep maxminddb" gives:

```
libmaxminddb.so.0 (libc6,x86-64) => /usr/local/lib/libmaxminddb.so.0
libmaxminddb.so (libc6,x86-64) => /usr/local/lib/libmaxminddb.so
```

However, when I configure nginx with ngx_http_geoip2_module, it complains:

```
adding module in /home/cilium/ngx_http_geoip2_module
checking for MaxmindDB library ... not found
./configure: error: the geoip2 module requires the maxminddb library.
```

I download the latest source of ngx_http_geoip2_module directly from Github. Any idea?

**Comment by PriteshJain** [comment]
moving it before all other add-module flags helped me too Thanks :+1:

**Comment by xiuquanw** [comment]
Previously, I used 'yum install libmaxminddb' and got this error as well.
rebuilding libmaxminddb helped me.
`
wget https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz
tar -xzf libmaxminddb-1.3.2.tar.gz
cd libmaxminddb-1.3.2
./configure
make
make check
sudo make install
sudo ldconfig
`

**Comment by ganeshlohia** [comment]
I have the same library not found issue.
I tried all the above. I have compiled libmaxminddb and ldconfig -v | grep libmaxminddb shows:
```
/sbin/ldconfig.real: Path `/usr/local/lib' given more than once
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring

        libmaxminddb.so.0 -> libmaxminddb.so.0.0.7
/sbin/ldconfig.real: /lib32/ld-2.27.so is the dynamic linker, ignoring
```
Not sure if this is due to the other errors shown above. But libmaxminddb is there and I am
able to use the lookup tool mmdblookup which means libmaxminddb is working on my server.

I tried all the juggling by putting add module before and after everything other add module declaration but the problem of the library not found remains. I even tried to add-dynamic-module but the problem does not go.

Here is my ./configure command for your reference. I am trying to compile with Nginx 1.15.8
```
./configure --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/srv/www/nginx_error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --http-log-path=/srv/www/nginx_access.log --http-client-body-temp-path=/tmp/nginxtmpbody --http-proxy-temp-path=/tmp/nginxtmpproxy --http-fastcgi-temp-path=/tmp/nginxtmpfastcgi --with-openssl=/srv/download/openssl-1.1.1a  --with-openssl-opt='enable-ec_nistp_64_gcc_128' --user=nginx --group=nginx --with-http_realip_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_gunzip_module --without-http_autoindex_module --without-http_uwsgi_module --without-http_scgi_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_ssl_module --with-http_v2_module --add-module=/srv/download/ngx_http_geoip2_module-master --add-module=/srv/download/ngx_devel_kit-master --add-module=/srv/download/set-misc-nginx-module-master --add-module=/srv/download/ngx_cache_purge-master --add-module=/srv/download/headers-more-nginx-module-master --add-module=/srv/download/ngx_brotli --with-file-aio --without-http_userid_module --without-http_ssi_module --without-http_split_clients_module --without-http_memcached_module --with-http_v2_hpack_enc --with-threads --with-cc-opt='-I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -Wno-error=strict-aliasing -fstack-protector-strong -flto -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting -Wno-cast-function-type -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --with-pcre-jit --with-zlib=/srv/download/zlib
```
Can someone please help me? I am not very good at adding compile options for best performance and in case my compile options need improvement, please also suggest. Thanks for your help.

**Comment by cortex3** [comment]
@ganeshlohia Were you able to resolve this issue by any chance?
Changing the order of the add module didn't work for me either.

**Comment by ganeshlohia** [comment]
Hi,

Mu apology for late reply. I had since moved to use this
nginx auto build that takes care of maxmind and soo many
other things. Unfortunately, this was recently flagged as no
longer being operational.

https://github.com/hakasenyang/nginx-build

Regards
Ganesh B Lohia

**Comment by NangenX** [comment]
i'm using the Rocky Linux 9 and install the Nginx (1.20.1) from the default repo, and try to build the dynamic module and have facing the same issues, but solved with @xiuquanw solution, make folder and rebuilding libmaxminddb, and it's work for me
