### ISSUE TITLE
ngx_http_geoip2_module: ‘struct crypt_data’ has no member named ‘current_salt’

### ISSUE THREAD

**Issue by LanceDdot** [leev/ngx_http_geoip2_module#101]
I'm installing **GeoIP Module** pre-requisites on my **DigitalOcean Droplet (nginx/ubuntu)** and I encountered this problem when I type in ```make``` command.

```
src/os/unix/ngx_user.c: In function ‘ngx_libc_crypt’:
src/os/unix/ngx_user.c:26:7: error: ‘struct crypt_data’ has no member named ‘current_salt’
   26 |     cd.current_salt[0] = ~salt[0];
      |       ^
make[1]: *** [objs/Makefile:784: objs/src/os/unix/ngx_user.o] Error 1
make[1]: Leaving directory '/usr/local/src/nginx-1.13.12'
make: *** [Makefile:8: build] Error 2
```

Command executed before ```make``` was ```./configure --add-dynamic-module=/root/ngx_http_geoip2_module```.

I already performed ```sudo apt-get update``` and ```sudo apt-get upgrade``` as a trial and error to fix the problem, and no luck.

How to fix the issue? Thank you! 😢

**Comment by LanceDdot** [comment]
I didn't solve the issue. But I use Cloudflare to implement Geo-blocking with their Firewall rules. It solved the problem but it relied on Cloudflare. :'(

**Comment by harsxv** [comment]
Hello @aeVfT3uJ24EcX3tE 

I'm facing the same problem as you mentioned above. Can you share how you fix this issue?
Thank you.
