### ISSUE TITLE
Return values formatted in JSON

### ISSUE THREAD

**Issue by pcarrier** [leev/ngx_http_geoip2_module#104]
It's be fantastic to have an option to return the values loaded from the database as JSON literals, like `"string value"`, `-20.5` for doubles, `null` when not found, etc.

**Comment by leev** [comment]
I don't think this module should be responsible for handling different representation/views of the data.  This seems like something that could be handled by nginx or another module.  Eg https://github.com/kaltura/nginx-json-var-module.
