### ISSUE TITLE
Query on fetching the subdivisions names en  with default value if subdivisions are missing

### ISSUE THREAD

**Issue by AnoopPutta** [leev/ngx_http_geoip2_module#105]
I am using the geolite2 city database, and wanted to fetch the subdivisions.
I see that subdivisons is an array and is not available always.  So what is the ngxinx directive configuration if i have to fetch the names en in the subdivision only if it available.
 {
    "geoname_id": 
      702657 <uint32>
    "iso_code": 
      "09" <utf8_string>
    "names": 
      {
        "de": 
          "Luhansk" <utf8_string>
        "en": 
          "Luhansk" <utf8_string>
        "fr": 
          "Oblast de Louhansk" <utf8_string>
        "ru": 
          "Луганская область" <utf8_string>
      }
  }

**Comment by leev** [comment]
With the following config:

```
http {
    geoip2 /Users/lee/GeoIP2-City_20230321/GeoIP2-City.mmdb {
        $geoip2_data_city_name source=$http_x_ip subdivisions 0 names en;
    }

    server {
        listen       8080;

        location / {
            return 200 $geoip2_data_city_name;
        }
    }
}
```
It shows:
```
lee:~ $ curl http://localhost:8080 -H "X-IP: 8.8.8.8" -w "\n"
California
lee:~ $ curl http://localhost:8080 -H "X-IP: 1.1.1.1" -w "\n"

lee:~ $
```

Based on that you can use `$geoip2_data_city_name` and check if it's empty or not.
