### ISSUE TITLE
Support for nginx 1.24.0

### ISSUE THREAD

**Issue by fanpero87** [leev/ngx_http_geoip2_module#115]
Hi, 
When can we expect support for `nginx v1.24.0` ?
I just updated all linux packages and nginx got updated to the latest version and accordingly with the releases, the latest one has support for `1.23.0`.

Thanks

**Comment by fanpero87** [comment]
Here is the exact error I get from nginx after the update to the latest version
`module "/etc/nginx/modules/ngx_http_geoip2_module.so" version 1022001 instead of 1024000 in /etc/nginx/nginx.conf:9`
I had to remove the module from the config file to restart the nginx service.

**Comment by leev** [comment]
I've just compiled nginx-1.24.0 and the module and it has worked fine.  It sounds like you might be using the nginx-1.24.0 binary, but using the old geoip2 module compiled against the previous version of nginx.  You need to use the module compiled against 1.24.0

**Comment by fanpero87** [comment]
Hi,
It seems that I forgot to do this at the end:
`sudo cp -vi objs/ngx_http_geoip2_module.so /etc/nginx/modules/`
so my `nginx.conf` file was reading the old file instead of the new one. 
My mistake, I added the module again and nginx is running.

Thanks.
