### ISSUE TITLE
It is no possible to use space which is not between words

### ISSUE THREAD

**Issue by GeorgeHu6** [leev/ngx_http_geoip2_module#117]
when I use `$geoip2_country_iso_code "default= a" country iso_code;`, the value will be `a` without the space.

**Comment by GeorgeHu6** [comment]
For the same reason, it is impossible to set the default value to a single space.

**Comment by leev** [comment]
Is there really a use case for needing a default value of a single space, or a value starting with a space?  I'm sure you could use other nginx functionality to prepend this if you needed it.
