### ISSUE TITLE
How do I use curl to set up IP for different countries to test geoip2?

### ISSUE THREAD

**Issue by xuyangxy** [leev/ngx_http_geoip2_module#122]
My configuration is as follows:

``

      geoip2 /etc/geoip/GeoLite2-Country_20210629/GeoLite2-Country.mmdb 
        $geoip2_country_code country iso_code;
        $geoip2_country_name country names en;
     }
``

I come from China, I want to use curl to set up IP to access nginx, but every time the country is China, I would like to ask how to set the request header?

`curl -vv  -H "X-Real-IP: xx" -H "X-Forwarded-For: xx"  -H "IP: xx" -H "remote_addr:xx"  https://xxxx.com
`

All I get with the above order is China.

**Comment by leev** [comment]
See the README about using the `source` setting.  You can set something like `source=$http_x_forwarded_for`  and it will use the IP provided in the `X-Forwarded-For` header.
