### ISSUE TITLE
arm64 compatibility

### ISSUE THREAD

**Issue by cberni** [leev/ngx_http_geoip2_module#124]
I build as a dynamic module in a Ubuntu 20.04 **amd64** and nginx 1.20.2. This works perfect and it is running on ours Ubuntu 20.04 and 22.04 **amd64** with nginx 1.20.2.

But now I tried to build on Ubuntu 22.04  **arm64** and nginx 1.20.2. After get the file "ngx_http_geoip2_module.so" we get the error bellow:

```
nginx -t
nginx: [emerg] module "ngx_http_geoip2_module.so" is not binary compatible in geoip.conf:1
nginx: configuration file nginx.conf test failed
```

does anybody could help? Is the "ngx_http_geoip2_module" not compatible with **arm64**?

**Comment by leev** [comment]
It is compatible.  You need to ensure you compile the module with the same flags that you compiled nginx with.   See #82 and #91
