### ISSUE TITLE
Error with NGINX 1.24

### ISSUE THREAD

**Issue by Talisker69** [leev/ngx_http_geoip2_module#127]
Hi,
Have you try with the latest stable version of nginx (1.24) ? 
On my side I have an error when I try to launch the module ... 
nginx: [emerg] module "/etc/nginx/ngx_http_geoip2_module.so" is not binary compatible in /etc/nginx/nginx.conf:13

**Comment by OSPanel** [comment]
You need to recompile the module

**Comment by Talisker69** [comment]
Ok thanks, it's works

**Comment by nerijus** [comment]
Please close the issue then.
