### ISSUE TITLE
Where can we get list of variables for the geopi2 databases?

### ISSUE THREAD

**Issue by encryptblockr** [leev/ngx_http_geoip2_module#131]
I am using the maxmind geolite2-city.mmdb database and for some reason am not able to get the city data

so am not sure if am using the correct variable to get the city data or it is just not available in the database

so my question is **where are the variable names documented so i can know exactly what the variable names are?** or we just have to be guessing the variable names???

here is what i have and **all the values get populated except the city one**

so is this wrong? `$geoip2_data_city_name`? anyways again where are these variable names documented to see all the available ones and the correct names

```
load_module modules/ngx_http_geoip2_module.so;


    geoip2 /usr/share/GeoIP/GeoLite2-City.mmdb {
        $geoip2_data_country_iso_code country iso_code;        # Country ISO code
        $geoip2_data_city_name city names;                  # City name
        $geoip2_data_postal_code postal code;                  # Zip/Postal code
        $geoip2_data_latitude location latitude;               # Latitude
        $geoip2_data_longitude location longitude;             # Longitude
    }



    log_format main '[$time_local] $http_cf_connecting_ip - $remote_user "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" '
                    '"Country: $geoip2_data_country_iso_code, '
                    'City: $geoip2_data_city_name, '
                    'Postal Code: $geoip2_data_postal_code, '
                    'Lat: $geoip2_data_latitude, '
                    'Long: $geoip2_data_longitude"';
```

**Comment by leev** [comment]
The README contains information about querying the MMDB database, seeing it's structure and converting that into the required configuration for the module.
