### ISSUE TITLE
First Non Private IP in X-Forwarded-For

### ISSUE THREAD

**Issue by ronb-ironsrc** [leev/ngx_http_geoip2_module#16]
@leev I was wondering if there are any plans in the near future to add some of the features that exist in the legacy apache module for GeoIP2. I am interested in the GeoIPUseFirstNonPrivateXForwardedForIP On described in the http://dev.maxmind.com/geoip/legacy/mod_geoip2/

**Comment by idyedov** [comment]
why not use nginx built-in realip module for that?
http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by leev** [comment]
As @idyedov said, there is the realip module.  It doesn't allow for stripping out private IP space though I don't think.

I had no plans to implement it, but could put it on the todo list if it was wanted.

**Comment by ronb-ironsrc** [comment]
Hi guys, actually the feature from the apache module for Geoip2 i mentioned above looks for the first non private ip starting from the left where as in the case of real ip module gets the first one starting from the right, if i'm not mistaken.

**Comment by realknorke** [comment]
The first non-private IP from left may be a bad idea. Every client is able to set X-Forwarded-For with an artificial (read: public) IP adress. Thus, nginx' default behaviour (the last untrusted IP adress in the list) may be better.
