### ISSUE TITLE
Retrieving Geo Data from the Traits Object

### ISSUE THREAD

**Issue by obihill** [leev/ngx_http_geoip2_module#17]
I am able to get country_code, continent_code, latitude, and longitude.

However, I can't seem to figure out how to get data that should be under **traits** object e.g. ISP, Autonomous System Number, etc. 

Below is what I have so far, but it's not working:

```
geoip2 /etc/maxmind-city.mmdb {
        $geoip2_traits_isp traits isp;
    }
```

Kindly assist.

**Comment by leev** [comment]
```
# mmdblookup --file GeoLite2-City.mmdb --ip 8.8.8.8 traits isp
Got an error looking up the entry data - The lookup path does not match the data (key that doesn't exist, array index bigger than the array, expected array or map where none exists)
```

**Comment by oschwald** [comment]
ISP and ASN are not in the GeoIP2/GeoLite2 City databases. They are available in the GeoIP2 ISP database, which, I believe, should work with this module.

**Comment by obihill** [comment]
@oschwald Thanks for the info. Is the GeoIP2 ISP Database in the same .mmdb format and is it free. I can't seem to find anything via Google Search. 
@leev Thanks. I'm not that savvy with your module so I don't really understand your response.

**Comment by oschwald** [comment]
@obihill, the [GeoIP2 ISP database](https://www.maxmind.com/en/geoip2-isp) is available as an mmdb file, but it is not free.

**Comment by obihill** [comment]
@oschwald Thanks a lot.
