### ISSUE TITLE
disk io

### ISSUE THREAD

**Issue by abitlate** [leev/ngx_http_geoip2_module#21]
Tried to load GeoIP2-Connection-Type database but disk io increased and server died in few minutes.  

here is configuration file

geoip2  /usr/share/geoip2/GeoIP2-Connection-Type.mmdb
{
$geoip2_connection_type   connection_type;
}

Any idea what is causing this?  

-vij

**Comment by leev** [comment]
Unfortunately I'm not sure.  The module uses libmaxminddb (https://github.com/maxmind/libmaxminddb) to handle looking up the data.  I would suggest taking a look at how that works to see why you're seeing the increased disk io.
