### ISSUE TITLE
Accessing different columns other than country and city

### ISSUE THREAD

**Issue by scaryguy** [leev/ngx_http_geoip2_module#24]
Hi there,

I've been using legacy .DAT format for Maxmind GeoIP db. I'm considering to use your module and the new format of Maxmind. But I wonder if there is a way to access a specific column of the db (in my case it's subdivision_1_name)? I'm getting the column name looking at CSV version of new format. http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip

Thank you

**Comment by leev** [comment]
Hi,

I've been meaning to update the readme to contain this.  If you use the mmdblookup tool provided with libmaxminddb, you can dump out what a record looks like:

```
$ mmdblookup --file /usr/share/GeoIP/GeoIP2-Country.mmdb --ip 8.8.8.8
  {
    "continent": 
      {
        "code": 
          "NA" <utf8_string>
        "geoname_id": 
          6255149 <uint32>
        "names": 
          {
            "de": 
              "Nordamerika" <utf8_string>
            "en": 
              "North America" <utf8_string>
            ...
          }
      }
    "country": 
      {
        "geoname_id": 
          6252001 <uint32>
        "iso_code": 
          "US" <utf8_string>
        "names": 
          {
            "de": 
              "USA" <utf8_string>
            "en": 
              "United States" <utf8_string>
            ...
          }
      }
      ...
  }
```

From this, you can determine how to select the field, eg: "country names en" will give you the country name in English.

**Comment by scaryguy** [comment]
Thanks for the answer! I'll give it a try once I turn back that part of the project.

By the way, this module looks a little bit outdated. Do you still maintain it? And do you think that it's something to be used in production? Thank you!

**Comment by leev** [comment]
See #23
