### ISSUE TITLE
Possible to use alternative IP Address header when getting GEO Data?

### ISSUE THREAD

**Issue by cpats007** [leev/ngx_http_geoip2_module#26]
HI. I was wondering if it was possible to be able to use an IP Address in a different header for the IP detection logic - so we could basically pass something through like my_ip_header and use that to obtain the geo data using your module in NGINX?

Hope that makes sense.

Cheers

**Comment by leev** [comment]
Hi Craig,

You can use the nginx realip module (http://nginx.org/en/docs/http/ngx_http_realip_module.html) for this.

Cheers,
Lee

**Comment by cpats007** [comment]
Thanks for the reply Lee

Will this allow me to change the IP to a header field before the module makes it’s GEO lookup?

Just wanted to check really.

Thanks again for the quick reply

**Comment by leev** [comment]
Correct.
