### ISSUE TITLE
Which variables are exposed?

### ISSUE THREAD

**Issue by Roycohen** [leev/ngx_http_geoip2_module#30]
Can we expose the same variables as the official legacy module.
http://nginx.org/en/docs/http/ngx_http_geoip_module.html

Region and other data that can be fetch.

**Comment by leev** [comment]
Looking at the original module, it might not work as those variables are predefined in there.  If your nginx is compiled without that module it will be fine.

**Comment by Roycohen** [comment]
So compiling NGINX with this module and not with the official module will be fine and I would have all the variables exposed? Are you sure?

**Comment by leev** [comment]
No, I'm not sure as I haven't needed to do this.  It would be quite easy to compile nginx with this module, write a base config to do what you need and test it though.
