### ISSUE TITLE
./configure: error: no /etc/nginx/modules/ngx_http_geoip2_module/config was found

### ISSUE THREAD

**Issue by gabayliran** [leev/ngx_http_geoip2_module#34]
`centos-release-7-2.1511.el7.centos.2.10.x86_64`
`nginx-1.10.2`

keep getting the error message `./configure: error: no /etc/nginx/modules/ngx_http_geoip2_module/config was found`

when I try `./configure --add-dynamic-module=/etc/nginx/modules/ngx_http_geoip2_module`

Any idea why ?

**Comment by gabayliran** [comment]
maybe because this issue?
https://github.com/maxmind/libmaxminddb/issues/128

**Comment by khalilst** [comment]
I've downloaded `libmaxminddb-1.3.2.tar.gz` and installed it according to its readme.
However the same error happens again.
@devopsberlin  How did you solved this issue?

**Comment by lhermann** [comment]
What the guide "forgets" to mention (maybe because it is implied): You have to actually download this repository (`git clone`) and then `/etc/nginx/modules/ngx_http_geoip2_module` is the path to your copy of this repository.
