### ISSUE TITLE
module "/ngx_stream_geoip2_module.so" version 1011005 instead of 1011006

### ISSUE THREAD

**Issue by dev6** [leev/ngx_http_geoip2_module#37]
Getting this error from nginx while following the instructions from here used to build this module 

```
nginx: [emerg] module "/usr/lib/nginx/modules/ngx_stream_geoip2_module.so" version 1011005 instead of 1011006 in /etc/nginx/nginx.conf:8
```
I think this is because of recent updates to this library because it was working just fine a few days back and today when I decided to build nginx on a new machine pulling with this module latest repo.

**Comment by leev** [comment]
It looks like the module was compiled against 1.11.5 where as the nginx version you're running is 1.11.6.  The module needs to be compiled against the same version of nginx that you're running.

**Comment by dev6** [comment]
Yes, that was the issue and its working good now when compiled with 1.11.6
