### ISSUE TITLE
Undefined symbol "ngx_stream_complex_value"

### ISSUE THREAD

**Issue by serge-vk** [leev/ngx_http_geoip2_module#42]
Hi, I am not sure if this is the right place to ask this question. For a long while now, I have been unable to load into Nginx the dynamic module ngx_stream_geoip2_module.so with the following error in the nginx log:
```
nginx: [emerg] dlopen() "/usr/local/libexec/nginx/ngx_stream_geoip2_module.so" failed (/usr/local/libexec/nginx/ngx_stream_geoip2_module.so: Undefined symbol "ngx_stream_complex_value") in /usr/local/etc/nginx/nginx.conf:9
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```
I run www/nginx-devel port on FreeBSD, and when I tried building/using your module, I've always got this error (it persisted through a few updates already). All the other modules I tried so far work without problem and I wonder what is missing.

Thanks in advance.

**Comment by defanator** [comment]
@serge-vk, which version of nginx are you using? Could you please share full output of the `nginx -V` command?

**Comment by defanator** [comment]
@serge-vk, also, could you please share your nginx.conf?

According to https://svnweb.freebsd.org/ports/head/www/nginx-devel/Makefile?view=markup#l1065, stream module can be built as a dynamic module. In this case it should be loaded **before** any other modules which are using stream features (like geoip2), otherwise there may be errors from `dlopen()` similar to the one mentioned in your initial message here.

**Comment by serge-vk** [comment]
Hi, thank you for your response. In my ports configuration, nginx is built with dynamic module support, and accordingly, `geoip2` is loaded dynamically. This is the top of my `nginx.conf`:
```
load_module /usr/local/libexec/nginx/ngx_http_brotli_filter_module.so;
load_module /usr/local/libexec/nginx/ngx_http_brotli_static_module.so;
# nginx -t fails with the reported error on the following line
load_module /usr/local/libexec/nginx/ngx_stream_geoip2_module.so;
load_module /usr/local/libexec/nginx/ngx_http_geoip2_module.so;
```
In fact, to spare you the pain of going through my nginx.conf, I've just tested a configuration with exactly the four lines above, and it generated the same error as originally reported. 

Here is the output of `nginx -V`:
```
nginx version: nginx/1.13.0
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --add-module=/var/ports/usr/ports/www/nginx-devel/work/ngx_cache_purge-2.3 --add-dynamic-module=/var/ports/usr/ports/www/nginx-devel/work/echo-nginx-module-46334b3 --add-dynamic-module=/var/ports/usr/ports/www/nginx-devel/work/ngx_http_geoip2_module-2.0 --with-http_gzip_static_module --with-http_gunzip_module --with-http_perl_module=dynamic --add-module=/var/ports/usr/ports/www/nginx-devel/work/ngx_http_response-0.3 --add-module=/var/ports/usr/ports/www/nginx-devel/work/ngx_http_substitutions_filter_module-0.6.4 --with-http_secure_link_module --with-http_slice_module --with-http_stub_status_module --with-http_sub_module --add-module=/var/ports/usr/ports/www/nginx-devel/work/modsecurity-2.9.1/nginx/modsecurity --with-pcre --add-module=/var/ports/usr/ports/www/nginx-devel/work/redis2-nginx-module-0.12 --with-http_v2_module --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-http_ssl_module --add-dynamic-module=/var/ports/usr/ports/www/nginx-devel/work/ngx_brotli-ada972b
```
So far, `nginx` has been working for me as a NextCloud server without any problem ever since NextCloud was forked (pretty much with unchanged configuration). I only failed so far to use `geoip2`. I'll be happy to do more testing if necessary.

**Comment by defanator** [comment]
@serge-vk, I've just reproduced the issue with nginx/1.13.0 on FreeBSD 11. The reason of failure is in displacement of the `load_module` directive for the stream module itself. The following patch to the nginx.conf fixes the issue:

```
[root@fbsd11-amd64-defan1 /usr/local/etc/nginx]# diff -u nginx.conf.orig nginx.conf
--- nginx.conf.orig	2017-05-15 19:49:04.838259000 +0000
+++ nginx.conf	2017-05-15 19:49:10.583299000 +0000
@@ -1,7 +1,7 @@
+load_module /usr/local/libexec/nginx/ngx_stream_module.so;
 load_module /usr/local/libexec/nginx/ngx_http_geoip2_module.so;
 load_module /usr/local/libexec/nginx/ngx_stream_geoip2_module.so;
 load_module /usr/local/libexec/nginx/ngx_mail_module.so;
-load_module /usr/local/libexec/nginx/ngx_stream_module.so;
 
 #user  nobody;
 worker_processes  1;
```

Perhaps this should be reported to the `www/nginx-devel` port maintainer (@osokin).

**Comment by serge-vk** [comment]
Oh, great, many thanks. Indeed, the `ngx_stream_module.so` was loaded *after* `geoip2`. I do not remember editing the module load sequence. In fact, I just looked up the original automatically generated default `nginx.conf` in a separate jail. And there, `ngx_stream_module.so` was placed at the end of `load_module` block. 

I will report this at `www/nginx-devel` and make a reference to this thread.
