### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by chabior** [leev/ngx_http_geoip2_module#43]
While `make` I've got error:
> /usr/bin/ld: objs/addon/ngx_geoip2/ngx_http_geoip2_module.o: relocation R_X86_64_PC32 against symbol `ngx_http_geoip2_module' can not be used when making a shared object; recompile with -fPIC

I am trying to complie with nginx 1.10.0 on ubuntu (i've got this error on two different ubuntu versions).

**Comment by romaka** [comment]
Did you manage to solve this?

**Comment by chabior** [comment]
Nope

**Comment by leev** [comment]
As this is almost 1.5 years old now, I'm closing.
