### ISSUE TITLE
support for x_forwarded_for

### ISSUE THREAD

**Issue by nikhilgarg789** [leev/ngx_http_geoip2_module#44]
We are trying to run this module using IP value set in x_forwarded_for header. Is there any way to achieve this?

**Comment by leev** [comment]
You have multiple options.  

If there is only 1 ip in the header, you can just use source=$http_x_forwarded_for.

You can use the realip module.

You can use the geoip2_proxy command.  It works the same as geoip_proxy defined here: http://nginx.org/en/docs/http/ngx_http_geoip_module.html#geoip_proxy
