### ISSUE TITLE
How to get Subdivisions

### ISSUE THREAD

**Issue by muditdixit7** [leev/ngx_http_geoip2_module#46]
Subdivision data type is array.While country and city are of objects.I am able to successfully fetch country and city data but not subdivisions.Can you please elaborate on how to fetch whole subdivision array and nth object in subdivisions array.

I had used the following code below to fetch subdivisions but was unable to so.
`$geoip2_data_subdivision_name source=$http_x_forwarded_for subdivisions names en;`

**Comment by muditdixit7** [comment]
Was able to fetch 0th subdivision element using this :
`$geoip2_data_subdivision_code source=$http_x_forwarded_for subdivisions 0 iso_code;`

**Comment by AnoopPutta** [comment]
Hi [muditdixit7](https://github.com/muditdixit7)

what if. there are no subdivisions at all? Does this throw any error? 
Appreciate if any poinnters.
