### ISSUE TITLE
http_x_forwarded_for ip not getting picked up.

### ISSUE THREAD

**Issue by muditdixit7** [leev/ngx_http_geoip2_module#47]
Im setting `http_x_forwarded_for` in my request but `ngx_http_geoip2_module` module is not picking the forwaded ip and providing me geoip information of ip with which request is sent.

**Comment by leev** [comment]
#44

**Comment by muditdixit7** [comment]
My use case is :
1) I want the ip information with which request is sent if http_x_forwarded_for is not set.`
2) I Want the ip information of forwaded ip if http_x_forwarded_for is set.

Any way to achieve this.Currently i am able to achieve only one of the 2 mentioned above by setting 
source = http_x_forwarded_for

**Comment by leev** [comment]
Then you want the realip module.
