### ISSUE TITLE
Read client IP from custom variable

### ISSUE THREAD

**Issue by donbeave** [leev/ngx_http_geoip2_module#5]
Hello!

Is it possible to specify from which variable read client IP?

I think to integrate this module with PowerDNS through remote backend, so it will be awesome if I can use `$http_x_remotebackend_real_remote` variable.

**Comment by leev** [comment]
As an update, you can now do this:

```$geoip2_data_country_code default=GB source=$variable country iso_code;```

**Comment by donbeave** [comment]
@leev Thanks! Useful feature.
