### ISSUE TITLE
Access last subdivisions

### ISSUE THREAD

**Issue by mthoretton** [leev/ngx_http_geoip2_module#57]
Hello,

I'm struggling with accessing the "last" `subdivisions` element.
```
  geoip2        /etc/nginx/GeoIP2-City.mmdb {
    $geoip_region_name subdivisions 0 names en;
  }
```
Is working well, but I cannot find a way to get the "last" index instead of "0". I've tried with -1 for instance.
Not sure it's an nginx or this module specific syntax.

Would be interested to know if there is a simple way, otherwise I guess I can work around it with nginx directives.

Thanks

**Comment by mthoretton** [comment]
This is the workaround I'll use for now:
```
  geoip2        /etc/nginx/GeoIP2-City.mmdb {
    $geoip2_city_subdivisions_name0 subdivisions 0 names en;
    $geoip_region_name subdivisions 1 names en;
  }

  rewrite_by_lua '
    if ngx.var.geoip_region_name == nil then
      ngx.var.geoip_region_name = ngx.var.geoip2_city_subdivisions_name0
    end
  ';
```

**Comment by leev** [comment]
The path (eg `subdivisions 0 names en`) is passed to the maxmind library which parses it and finds the object.  To be able to lookup the `last` item, it would need to be implemented in that library.
