### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by AndriiZ** [leev/ngx_http_geoip2_module#66]
Linux bananapi 4.14.84-sunxi #3 SMP Sat Dec 1 07:18:41 CET 2018 armv7l GNU/Linux

-ldl -lpthread -lpthread -lcrypt -lmaxminddb -lmaxminddb ../pcre-8.42/.libs/libpcre.a ../openssl-1.1.0h/.openssl/lib/libssl.a ../openssl-1.1.0h/.openssl/lib/libcrypto.a -ldl -lpthread ../zlib-1.2.11/libz.a \
-Wl,-E
objs/addon/ngx_http_geoip2_module/ngx_stream_geoip2_module.o: In function `ngx_stream_geoip2_init':
/media/usb/src/nginx/ngx_http_geoip2_module/ngx_stream_geoip2_module.c:697: undefined reference to `ngx_stream_core_module'
objs/addon/ngx_http_geoip2_module/ngx_stream_geoip2_module.o: In function 
`ngx_stream_geoip2_add_variable_metadata':
/media/usb/src/nginx/ngx_http_geoip2_module/ngx_stream_geoip2_module.c:478: undefined reference to `ngx_stream_add_variable'
objs/addon/ngx_http_geoip2_module/ngx_stream_geoip2_module.o: In function `ngx_stream_geoip2_add_variable_geodata':
/media/usb/src/nginx/ngx_http_geoip2_module/ngx_stream_geoip2_module.c:550: undefined reference to `ngx_stream_compile_complex_value'
/media/usb/src/nginx/ngx_http_geoip2_module/ngx_stream_geoip2_module.c:566: undefined reference to `ngx_stream_add_variable'
objs/addon/ngx_http_geoip2_module/ngx_stream_geoip2_module.o: In function `ngx_stream_geoip2_variable':
/media/usb/src/nginx/ngx_http_geoip2_module/ngx_stream_geoip2_module.c:136: undefined reference to `ngx_stream_complex_value'
collect2: error: ld returned 1 exit status
objs/Makefile:348: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/media/usb/src/nginx/nginx-1.15.8'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by fabiosussetto** [comment]
@AndriiZ Did you manage to fix this? getting the same error on Ubuntu 16.04. Thanks.

**Comment by sc0rp10** [comment]
@fabiosussetto use `--with-stream` instead of `--with-stream=dynamic`

**Comment by fabiosussetto** [comment]
@sc0rp10 thanks, I don't have the chance to try it out now, but appreciate you answer!

**Comment by sc0rp10** [comment]
my comment is for the googlers :)
