### ISSUE TITLE
error with installation

### ISSUE THREAD

**Issue by NathanQ** [leev/ngx_http_geoip2_module#71]
Current installed version Nginx is 1.14.0.

Steps taken:

- Downloaded the nginx version, configure, make and copied the so file to modules available and pointed the load_module in the nginx.conf to the so file. 
- I've tried configure with the `--make-compatible` flag. 
- I've tried the configure and make steps as sudo.
- I've tried the configure with the `--make-compatible` flag and make steps as sudo.

Each time, ran nginx -t and:
`nginx: [emerg] module "/etc/nginx/modules-available/ngx_http_geoip2_module.so" is not binary compatible in /etc/nginx/nginx.conf`

What am I missing?

Thank you!

**Comment by HooK81** [comment]
Exactly the same error with Nginx 1.10.3 installed with package manager.

The module was compiled with Nginx source 1.10.3

systemctl status Nginx:
`nginx: [emerg] module "/usr/share/nginx/modules/ngx_http_geoip2_module.so" is not binary compatible in /etc/nginx/modules-enabled/50-ngx_http_geoip2_module.conf:
`

If someone has a solution it will be cool.

**Comment by leev** [comment]
Are you compiling the module against the same version of nginx you're trying to run it in?

**Comment by NathanQ** [comment]
@leev. Yes. Same version. Ooh, now I haven't tried upgrading or a different version...  I'll follow up. Thanks.

**Comment by NathanQ** [comment]
@leev I upgraded Nginx to 1.14.2 and tried again with the same result: `nginx: [emerg] module "ngx_http_geoip2_module.so" is not binary compatible in /etc/nginx/nginx.conf`

**Comment by philiprabbett** [comment]
The flags you use in `./configure` when building `ngx_pagespeed.so` should be the same as the one specified when building the nginx binary. You can use `nginx -V` to list the configure arguments. Could you try this and see if that solves the binary compatibility issue?

_Originally posted by @oschaaf in https://github.com/apache/incubator-pagespeed-ngx/issues/1135#issuecomment-226489650_

**Comment by oschaaf** [comment]
In addition to what @philiprabbett  posted above, if that still doesn't result in a compatible library, the following may also still be relevant: https://github.com/apache/incubator-pagespeed-ngx/issues/1440#issuecomment-315565106

(TL;DR `-DNGX_HTTP_HEADERS` may not show up in `nginx -V`, but still be needed)

**Comment by dvershinin** [comment]
There is no any `--make-compatible` flag. The flag you should all be using is ` --with-compat`. More about binary compatible NGINX module builds [here](https://www.nginx.com/blog/nginx-dynamic-modules-how-they-work/#compatibility).

Side note. For CentOS / RHEL 7, there are module packages for both this module and ngx_pagespeed. Can be installed with:

    yum -y install https://extras.getpagespeed.com/release-el7-latest.rpm
    yum install nginx nginx-module-geoip2 nginx-module-nps
