### ISSUE TITLE
ASN lockup sample?

### ISSUE THREAD

**Issue by mhf-ir** [leev/ngx_http_geoip2_module#76]
```bash
sweb@sweb-laptop:~$ mmdblookup -f ~/GeoLite2-ASN.mmdb -i 8.8.8.8

  {
    "autonomous_system_number": 
      15169 <uint32>
    "autonomous_system_organization": 
      "Google LLC" <utf8_string>
  }
```

How to get it inside this module in nginx ?

It's free and available : https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by leev** [comment]
You use `autonomous_system_number` or `autonomous_system_organization` as the path inside the `geoip2` block.  Eg:

`$geoip2_asn autonomous_system_number;`
