### ISSUE TITLE
Please add nat64 support for all kind of lookups

### ISSUE THREAD

**Issue by ruben-herold** [leev/ngx_http_geoip2_module#78]
hi,

I have some systems behind a nat64 (https://de.wikipedia.org/wiki/NAT64).
So the module must retranslate the NAT64 address to the original ipv4. Example:

64:ff9b::c000:201 --> 64:ff9b::192.0.2.1 --> 192.0.2.1

The NAT64 prefix should be configurable cause many system uses prefix from their own global local space for this.

**Comment by leev** [comment]
This isn't what the module is for.  The module is for taking a known IP and doing the lookup.  You should investigate something like the realip module (http://nginx.org/en/docs/http/ngx_http_realip_module.html) to see if it can do what you need.
