### ISSUE TITLE
Any plan to add to nginx core module?

### ISSUE THREAD

**Issue by mhf-ir** [leev/ngx_http_geoip2_module#79]
I think time to use this module instead of deprecated geoip module.

https://support.maxmind.com/geolite-legacy-discontinuation-notice/

**Comment by leev** [comment]
Thats a decision for the nginx core team, not me.

**Comment by mhf-ir** [comment]
https://trac.nginx.org/nginx/ticket/1857

I'v already ask them, so wait to response.
BTW this module is essential, Thanks for create it.
