### ISSUE TITLE
[Help]How can I use the first one ip in the xff?

### ISSUE THREAD

**Issue by myf5** [leev/ngx_http_geoip2_module#80]
Hi,
With xff as source, assume xff value is:  1.1.1.1,2.2.2.2,3.3.3.3
how can I get the 1.1.1.1 as value?
`geoip2 geoip/GeoLite2-City.mmdb {
       $geoip2_data_city_name source=$http_x_forwarded_for city names en;
    }`
Many thanks

**Comment by leev** [comment]
See #44
