### ISSUE TITLE
New variables can't be used as source

### ISSUE THREAD

**Issue by artembokhan** [leev/ngx_http_geoip2_module#88]
If variable is defined inside configuration file it can't be used as source. Please fix if possible.

    geoip2 /usr/share/GeoIP/GeoLite2-City.mmdb {
        auto_reload 5m;
        $country_code   source=$ipaddress country iso_code;
        $country_name   source=$ipaddress country names en;
        $city_name      source=$ipaddress city names en;
        $continent_name source=$ipaddress continent names en;
        $continent_code source=$ipaddress continent code;
    }

nginx -t
nginx: [emerg] unknown "ipaddress" variable
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by wronan** [comment]
I think you must have messed something up in the config, because I'm using such a solution in one of my apps and it's working fine (different sources for the IP to geolocated, variable set in the main file, geoip2 directives loaded from `conf.d/`)

**Comment by abokhan** [comment]
I have a workaround using variable $http_variable (aka request header) which is working but not with $variable

**Comment by artembokhan** [comment]
I have a workaround using variable $http_variable (aka request header) which is working but not with $variable

**Comment by artembokhan** [comment]
Variable must be defined to use it. I was trying to use variable from named capture group which did not work.

**Comment by seguri** [comment]
@wronan can you please show me the content of your configuration file from `conf.d`?

**Comment by wronan** [comment]
Sorry man... I've switched to other solution long time ago and the config is gone.
