### ISSUE TITLE
only ET_DYN and ET_EXEC can be loaded

### ISSUE THREAD

**Issue by olegsidokhmetov** [leev/ngx_http_geoip2_module#94]
after restart nginx I have errors

`root@NC-V3:/usr/share/nginx/modules# nginx -t`
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_geoip2_module.o" failed (/etc/nginx/modules/ngx_http_geoip2_module.o: only ET_DYN and ET_EXEC can be loaded) in /etc/nginx/nginx.conf:5

`root@NC-V3:/usr/share/nginx/modules# ls /etc/nginx/modules`
ngx_http_geoip2_module.o

**How I can solve this problem?**

**Comment by leev** [comment]
You need to build nginx/module with dynamic support.  When you do this, you'll get a `ngx_http_geoip2_module.so` file (notice `.so`, not `.o`) and you use that.
See: https://www.nginx.com/resources/wiki/extending/converting/
