### ISSUE TITLE
IP Database Confusion

### ISSUE THREAD

**Issue by axellageraldinc** [leev/ngx_http_geoip2_module#99]
Hi, I've read the readme file and it says that it's optional to download the geolite database > https://github.com/leev/ngx_http_geoip2_module#download-maxmind-geolite2-database-optional
But I also see that we must provide a path to the .mmdb file when using the geoip2 library, which I assume that we store our own .mmdb file.

So, does this library access our own stored .mmdb file or not?
Thank you in advance.

**Comment by leev** [comment]
The library needs a Maxmind database file.  The readme has it as optional as you might be using another version of the database the you already have a copy (eg commerical/paid for version).  But if you're not, you will need to download the free one.
